service_name = "adcp-processor"
mode = "Processing"
serial_port = "/dev/null"
data_process_folder = "./deployment/to_process"
processed_folder = "./deployment/processed"
data_directory = "./deployment/data"
file_stability_seconds = 30
